camera:
  exposure_type: auto
  f_number: 16.0
  focal_length: 1.8
  pixel_format: Mono16
  target_brightness: 10
convert:
  gamma: 2.2
daemon:
  intervals: 600
default_exposures:
- 3000.0
- 300.0
- 30.0
- 3.0
- 0.3
- 0.03
default_nb_exposures: 5
default_step_size: 3
image:
  extension: tiff
last_location:
  alt: 1143.0
  lat: -24.8833
  lon: 28.2833
